reanahub/reana-db

- reana_db/models.py
* Examples such as `reana-demo-atlas-recast` use big commands and
when they are extended (i.e. all palceholders in a yadage step
are replaced which the actual values) they can be big as a bash
script (closes #6).
> models: increase `prettified_cmd` size

- reana_db/models.py
- reana_db/version.py
* Fixes Workflow.get_parameters() for the case of workflows without
inputs.
> models: fix get_parameters() for empty inputs

- reana_db/models.py
* Renaming operational_parameters to parameters,
get_parameters() to get_input_parameters().
Connects https://github.com/reanahub/reana-client/issues/200
> models: renaming operational parameters

- reana_db/models.py
* Since every computing bakcend has different names for errors,
we need an internal way of identifying them. It will be task of
each implementation to define the mapping between the specific
computing backend and REANA.
* Renames `job_type` to `backend` to hold the backend type string.
Connects reanahub/reana-job-controller/issues/118
Co-authored-by: Rokas Maciulaitis <rokas.maciulaitis@cern.ch>
> models: store REANA Job status

- reana_db/models.py
* Since internal K8S jobs restarts are disabled, these fields
are not needed anymore.
Addresses reanahub/reana-workflow-controller/issues/236
> models: removes restart counts

- reana_db/config.py
Closes reanahub/docs.reana.io#18.
> config: fix db host default to respect prefixing

- reana_db/version.py
- setup.py
SQLAlchemy-Utils stopped supporting python 2.7 in version 0.36.4
https://github.com/kvesteri/sqlalchemy-utils/releases/tag/0.36.4
> setup: pin SQLAlchemy-Utils to 0.36.3 for python 2

- reana_db/version.py
- setup.py
Due to `invenio-db` pinning to `SQLAlchemy-Utils<0.36,>=0.33.1` and
r`eana-server` pinning to `SQLAlchemy-Utils[encrypted]>=0.33.0,<0.36.0 `to
satisfy invenio's requirements.
>  setup: decrease sqlalchemy-utils min version 

- CHANGES.rst
- reana_db/config.py
- reana_db/version.py
- setup.py
* Uses the centrall host name for database which will include the
fully qualified domain name inside the cluster, including the
namespace enabling RJC to communicate to it from different
namespaces (closes reanahub/reana#268).
> config: uses central FQDN component name

- reana_db/version.py
- setup.py
Fixes problems with previous `reana-db` version not containing
`alembic.ini` due to which REANA production installation was failing.
Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>
> installation: include package data such as Alembic files

- reana_db/cli.py
- reana_db/models.py
- reana_db/utils.py
- tests/test_models.py
closes reanahub/reana-workflow-controller#333
closes #88
> cli: add command to update users disk quota usage

- reana_db/models.py
- reana_db/utils.py
- tests/conftest.py
- tests/test_models.py
closes #93
Steps to test it:
```bash
$ reana-dev cluster-undeploy && reana-dev cluster-deploy ...
$ kubectl exec -ti deployment/reana-db -- psql -U reana
reana=# select r.type_, wr.quantity_used, wr.workflow_id from __reana.resource as r join __reana.workflow_resource as wr on r.id_ = wr.resource_id;
type_ | quantity_used | workflow_id 
-------+---------------+-------------
(0 rows)
reana=# select r.type_, wr.quantity_used, wr.workflow_id from __reana.resource as r join __reana.workflow_resource as wr on r.id_ = wr.resource_id;
type_ | quantity_used |             workflow_id              
-------+---------------+--------------------------------------
cpu   |         24415 | 61a6ce6e-e173-4f66-bc60-34c9af07db81
disk  |        173734 | 61a6ce6e-e173-4f66-bc60-34c9af07db81
(2 rows)
```
> models: calculate disk workflow resource usage

- CHANGES.rst
- reana_db/models.py
- tests/test_models.py
E.g. "KiB", "MiB", "GiB", etc.
closes reanahub/reana#437
---
```console
$ reana-client quota-show --resource disk               
222.55 KiB out of 8.58 MiB used (3%)
```
> models: use powers of 1024 to display size units

- reana_db/version.py
- setup.py
Issue caused by an imcompatibility between sqlalchemy-utils
and latest SQLAlchemy 1.4 (Fix is already there, but invenio-db needs to be unpinned first)
> installation: temporarily pin SQLAlchemy<1.4 

- reana_db/alembic/versions/20201009_1612_ad93dae04483_interactive_sessions.py
- reana_db/alembic/versions/20210507_1240_4801b98f6408_job_started_and_finished_times.py
closes #127
To test:
```console
$ kubectl exec -ti deployment/reana-db -- psql -U reana
psql (9.6.2)
Type "help" for help.
reana=# \d __reana.job
Table "__reana.job"
Column       |            Type             | Modifiers 
--------------------+-----------------------------+-----------
...
finished_at        | timestamp without time zone | 
started_at         | timestamp without time zone | 
...
reana=# \q
$ kubectl exec deployment/reana-server reana-db alembic history
ad93dae04483 -> 4801b98f6408 (head), Job started and finished times.
c912d4f1e1cc -> ad93dae04483, Interactive sessions.
<base> -> c912d4f1e1cc, Quota tables.
$ kubectl exec deployment/reana-server reana-db alembic current
4801b98f6408 (head)
$ kubectl exec deployment/reana-server reana-db alembic downgrade ad93dae04483
INFO …
```
> alembic: add revision for job started/finished times

- reana_db/alembic/versions/20210607_1217_f84e17bd6b18_workflow_complexity.py
- reana_db/models.py
- reana_db/version.py
- setup.py
closes https://github.com/reanahub/reana-server/issues/358
```console
$ kubectl exec deployment/reana-server reana-db alembic history
4801b98f6408 -> f84e17bd6b18 (head), Workflow complexity.
ad93dae04483 -> 4801b98f6408, Job started and finished times.
c912d4f1e1cc -> ad93dae04483, Interactive sessions.
<base> -> c912d4f1e1cc, Quota tables.
$ kubectl exec deployment/reana-server reana-db alembic current
f84e17bd6b18 (head)
$ kubectl exec deployment/reana-server reana-db alembic downgrade 4801b98f6408
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running downgrade f84e17bd6b18 -> 4801b98f6408, Workflow complexity.
$ kubectl exec deployment/reana-server reana-db alembic …
```
> models: store workflow complexity

- reana_db/models.py
- reana_db/version.py
- tests/test_models.py
So workflow complexity is still relevant besides user reaching `max_concurrent_workflows`.
closes reanahub/reana-server#381
Check [this comment](https://github.com/reanahub/reana-server/issues/381#issuecomment-863962382) for reference.
> models: adjust wf overflow priority to avoid to be 0

- reana_db/models.py
Removes explicit type casting that is no longer necessary now that
Python 2 support is officially removed in the `master` branch.
> models: code simplification after removal of py27

- AUTHORS.rst
- reana_db/utils.py
- reana_db/version.py
- setup.py
- tests/test_utils.py
Quit the dependency of upload-file,remove-file, list-files,mv-files  and download, relying directly on the full-path stored in the database
Closes reanahub/reana-db#94
> models: modify workspace_path to store full path

- reana_db/utils.py
- setup.py
> utils: use default workspace path instead of shared workspace path  when the workspace root path is not declared

- reana_db/config.py
- reana_db/utils.py
- tests/test_models.py
Adapt assignment logic to avoid a list with an empty string `[""]`
when the policy coming from Helm is empty.
closes reanahub/reana#562
> config: adapt quota update policy to helm values

- reana_db/cli.py
- reana_db/config.py
- reana_db/models.py
- reana_db/utils.py
- tests/conftest.py
- tests/test_models.py
* moves cpu quota calculation logic into a function
* renames cli `disk-usage-update` cmd to `resource-usage-update` and includes cpu logic
* adds `update_users_cpu_quota` func to calculate all users' cpu quota
* adds tests covering functionality and various quota policy scenarios
closes https://github.com/reanahub/reana/issues/605
> quota: allow calculating cpu quota periodically

- reana_db/models.py
closes reanahub/reana-workflow-controller#430
This is the simplest solution. This PR prevents raising exceptions in the Workflow status event listener due to disk or CPU quota calculation errors. When an exception was raised before it terminated the workflow status update.
How to test:
1. Not easy, as I don't know the way to reproduce the error from the issue.
> models: catch exceptions in Workflow status listener

- CHANGES.rst
- reana_db/models.py
closes https://github.com/reanahub/reana-ui/issues/160
Change quota health status calculation to follow a traffic light analogy:
-  healthy (green), usage below <80%;
-  warning(yellow/brown), usage above 80% and below 100%;
-  critical (red), usage above 100%.
> models: change percentage ranges for calculating the quota health status

- CHANGES.rst
- reana_db/config.py
- reana_db/models.py
Considering issue #173, the limit is currently set to permit at most
nine restarts.
How to test: see #173
> models: limit the number of restarts of a workflow

- CHANGES.rst
- reana_db/models.py
- reana_db/utils.py
- reana_db/version.py
- setup.py
- tests/test_models.py
closes https://github.com/reanahub/reana-db/issues/172
To test:
- `kubectl exec -i -t deployment/reana-server -c rest-api -- invenio shell`:
```
from reana_db.models import Workflow, WorkspaceRetentionRule, WorkspaceRetentionRuleStatus
from reana_db.utils import update_workspace_retention_rules
from reana_db.database import Session
from datetime import datetime
s = Session()
workflow_id = Workflow.query.first().id_
workspace_files = "myfetched/**/*.root"
retention_days = 1
apply_on = None
wr = WorkspaceRetentionRule(workflow_id=workflow_id, workspace_files=workspace_files, retention_days=retention_days)
s.add(wr)
s.commit()
wr.status = WorkspaceRetentionRuleStatus.inactive
s.add(wr)
s.commit()
wr.audit_logs.all()
w = Workflow.query.first()
retention_rules = [
{
"workspace_files": …
```
> models: add workspace retention rules table

- reana_db/alembic/versions/20220711_1301_b92fe567be5b_retention_rules.py
Closes #175
How to test:
1. Deploy the previous version of the cluster
```diff
--- a/helm/configurations/values-dev.yaml
+++ b/helm/configurations/values-dev.yaml
@@ -2,25 +2,25 @@
components:
reana_server:
-      image: reanahub/reana-server
+      image: reanahub/reana-server:0.9.0-alpha.5
environment:
REANA_SCHEDULER_REQUEUE_SLEEP: 2
REANA_RATELIMIT_SLOW: "5 per second"
reana_workflow_controller:
-      image: reanahub/reana-workflow-controller
+      image: reanahub/reana-workflow-controller:0.9.0-alpha.5
environment:
REANA_RUNTIME_KUBERNETES_KEEP_ALIVE_JOBS_WITH_STATUSES: failed
reana_workflow_engine_cwl:
-      image: reanahub/reana-workflow-engine-cwl
+      image: reanahub/reana-workflow-engine-cwl:0.9.0-alpha.4
reana_workflow_engine_yadage:
-      image: …
```
> alembic: add migration for workspace retention rules

- CHANGES.rst
- reana_db/models.py
closes reanahub/reana-server#521
0. Try reproducing an error from the issue with disabled quota.
```diff
diff --git a/helm/reana/values.yaml b/helm/reana/values.yaml
index 487683b..e2b51ed 100644
--- a/helm/reana/values.yaml
+++ b/helm/reana/values.yaml
@@ -142,7 +142,7 @@ traefik:
quota:
-  enabled: true
+  enabled: false
periodic_update_policy: "{{ .Values.quota.disk_update }}"
workflow_termination_update_policy: "{{ .Values.quota.termination_update_policy }}"
```
1. Keep disabled quotas. Checkout the PR, run `reana-dev git-submodule --update`
2. Try to reproduce the issue again, it should not be possible
> models: always calculate disk usage for Workflow.get_workspace_disk_usage

- reana_db/models.py
- reana_db/version.py
This commit adds a new allowed transition from the status `pending` to the status `active`. This transition is needed when there are errors while applying the rule, so that it can be applied again in the future.
Closes reanahub/reana-server#559
> models: add new allowed transition for retention rules

- CHANGES.rst
- reana_db/models.py
Fix the workflow priority calculation to avoid dividing by zero and
causing workflows to be stuck in the ``queued`` status when the number
of allowed concurrent workflow is set to zero. The issue only affects
the "balanced" scheduling strategy.
Closes #195
> models: avoid dividing by zero in priority workflow calculation

- setup.py
Use the `encrypted` extra variant of `SQLAlchemy-Utils` instead of
specifying `cryptography` in `setup.py`.
Closes reanahub/reana-server#614
> setup: use `encrypted` extras of `SQLAlchemy-Utils`

- reana_db/cli.py
- reana_db/models.py
- reana_db/utils.py
- tests/test_models.py
quota: improve performance of quota updater
Improve the performance of the quota updater by "expunging" all
workflows before starting to update quotas, as the Workflow table does
not need to be modified, thus making commits much faster. Also refactor
the various update functions to make their behaviour consistent with
each other.
Partially addresses https://github.com/reanahub/reana-db/issues/193
> quota: improve performance of quota updater

- CHANGES.rst
- reana_db/models.py
- reana_db/utils.py
- tests/test_models.py
> quota: avoid accessing disk when updating user disk quotas

- run-tests.sh
Allows execution of selected pytests via PYTESTARG environment variable. Example:
```
$ PYTESTARG=tests/test_version.py ./run-tests.sh --check-pytest
```
Closes reanahub/reana#755.
> tests: allow execution of selected pytests only

- AUTHORS.rst
- CHANGES.rst
- reana_db/alembic/versions/20231002_1208_b85c3e601de4_separate_run_and_restart_number.py
- reana_db/config.py
- reana_db/models.py
- reana_db/utils.py
- tests/test_models.py
- tests/test_utils.py
Change the workflow table to split the run_number into two integers: one referring to the generation of the workflows, and the other one referring to the restart number, thus removing the limit of 9 restarts.
Closes #186.
---
To test the PR, these quick scripts might be come in handy:
1) Run the specified number of workflows on REANA (default 15), to be run from a workflow directory (such as roofit).
```shell
#!/bin/bash
NUM_RUNS=${1:-15}
eval $(reana-dev client-setup-environment)
for (( i=1; i<=NUM_RUNS; i++ ))
do
echo "Starting run $i of $NUM_RUNS..."
reana-client run -w root6-roofit
echo "Run $i submitted."
done
```
2) Restart a specific generation of the roofit demo workflow (default `1`) a certain number of times (default `15`). `./restart.sh 50 3` will restart `root6-roofit.3` 50 …
> models: replace workflow.run_number with generation and restart number

- CHANGES.rst
- reana_db/alembic/versions/20231128_1729_2461610e9698_enforce_naming_convention.py
- reana_db/alembic/versions/20231129_1356_eb5309f3d8ee_improve_indexes_usage.py
- reana_db/models.py
Add a new index to `__reana.job` on `workflow_uuid` and `created` to
query efficiently the jobs that are part of a given workflow, with the
possibility of ordering them by creation time.
Add a new index to `__reana.workflow` on `status` to efficiently query
the total number of running workflows.
Change the already-existing index on `__reana.workflow` so that
`owner_id` is the leading column, before `name`.
Closes #211
> models: improve indexes

- reana_db/models.py
- reana_db/version.py
- setup.py
- build(python): add support for SQLAlchemy 1.4 (#234)
- fix(models): remove duplicated relationship (#234)
Closes #228
> build(python): add support for SQLAlchemy 1.4 (#234)

- reana_db/alembic/versions/20240531_0959_86435bb00714_foreign_key_for_workflow_uuid_of_job.py
- reana_db/models.py
> fix(models): add missing foreign key to workflow_uuid of Job (#214) 

- AUTHORS.md
- reana_db/alembic/versions/20240828_1412_2e82f33ee37d_workflow_sharing.py
- reana_db/models.py
- reana_db/utils.py
- reana_db/version.py
Closes reanahub/reana-server#651, closes reanahub/reana-server#650
> utils: add permission error for getting workflows

- reana_db/cli.py
- reana_db/models.py
- reana_db/utils.py
Closes reanahub/reana-server#695
How to test:
1. Deploy 0.9.3
2. Save your REANA token
3. Deploy 0.9.4 (alpha)
4. Firstly, migrate invenio's secret key to the current one: `invenio instance migrate-secret-key --old-key CHANGE_ME`
5. Change the secret key and re-deploy
6. Restart reana-server: `kubectl rollout restart deployment reana-server`
7. Restart reana-workflow-controller: `kubectl rollout restart deployment reana-workflow-controller`
8. Migrate invenio's and REANA's secret keys: `invenio instance migrate-secret-key --old-key <old_key>` and `reana-db migrate-secret-key --old-key <old_key>` (if you didn't set a secret key in (1) and (3), then the old secret key is `secret_key`)
9. Test that you can see your token in the profile page of the web UI and that it's the same as (2)
> feat(cli): add new `migrate-secret-key` command (#240)

- AUTHORS.md
- reana_db/alembic/versions/20250117_1005_3d0994430da7_add_service_tables.py
- reana_db/models.py
- reana_db/version.py
This PR adds `Service` table to db. Currently, we have only `dask` service but it is a generic implementation and can be used for other components associated with workflows in the future.
> feat(models): add service tables
