AUTHORS.rst, CHANGES.rst, docs/api.rst, docs/configuration.rst, docs/index.rst, reana_db/models.py, reana_db/version.py
=> global: run release checklist

reana_db/models.py
* Adds reana_specification field in Workflow table.
* Adds operational_parameters field to contain parameters related to
the workflow engine execution.
Connects https://github.com/reanahub/reana-db/issues/12
=> models: reana_specification field in Workflow

.travis.yml, setup.py
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
=> installation: official support for Python-3.7

CHANGES.rst, docs/index.rst, reana_db/version.py
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
=> release: v0.4.0

reana_db/models.py
Connects https://github.com/reanahub/reana-client/issues/192
=> models: addition of deleted WorkflowStatus

reana_db/version.py
=> release: v0.5.0.dev20181116

reana_db/models.py, reana_db/version.py
Connects reanahub/reana-client#194.
=> models: add missing time stamp for stop workflow

reana_db/models.py, reana_db/version.py
=> models: append new line char in logs

reana_db/models.py, reana_db/version.py
Connects https://github.com/reanahub/reana-cluster/issues/154
=> models: Job fields to text

reana_db/models.py, reana_db/version.py
Connects reanahub/reana-workflow-controller#184.
=> workflow: add get owner access token

reana_db/models.py, reana_db/version.py
* Field containing the path to the currently opened interactive session.
Closes https://github.com/reanahub/reana-client/issues/258.
=> models: introduce interactive session field

reana_db/models.py
* Connects reanahub/reana-client/issues/247
=> models: new field for interactive session name

reana_db/version.py
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
=> release: v0.5.0.dev20190314

reana_db/models.py, reana_db/version.py, setup.py
* Connects reanahub/reana-client/issues/262
=> models: adding interactive_session_type

reana_db/models.py
* Connects reanahub/reana-job-controller/issues/122
=> models: save job env_vars & cmd as json

AUTHORS.rst, CHANGES.rst, docs/conf.py, reana_db/models.py, reana_db/utils.py, reana_db/version.py
=> release: 0.5.0

reana_db/models.py
=> models: adds new method returning workflow name

reana_db/models.py, reana_db/version.py
=> models: renames backend -> compute_backend

reana_db/models.py
Signed-off-by: Leticia Farias Wanderley <leticia.farias.wanderley@cern.ch>
=> models: add gitlab integration fields to workflow

reana_db/models.py
Signed-off-by: Leticia Farias Wanderley <leticia.farias.wanderley@cern.ch>
=> models: add git ref on workflow creation

reana_db/models.py, reana_db/version.py
addresses reanahub/reana-server#177
=> models: add git_repo and git_provider to workflow

reana_db/models.py, reana_db/version.py
addresses reanahub/reana-ui#50
=> models: add full name and username columns to user

reana_db/version.py, tests/test_utils.py, tests/test_version.py
Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>
=> version: post-release bump

reana_db/version.py
=> release: 0.7.0.dev20200129

reana_db/models.py, reana_db/utils.py, reana_db/version.py, tests/conftest.py, tests/test_models.py
* Saves workspace path column in order to allow reuse of
workspace.
* Addresses reanahub/reana-workflow-controller/issues/289
=> models: adds workspace_path column

reana_db/models.py, reana_db/version.py, tests/test_models.py
* Closes reanahub/reana-client#395.
=> models: initial workflow status transition logic

reana_db/models.py, reana_db/version.py, tests/conftest.py, tests/test_models.py
closes #18
closes reanahub/reana-ui#93
=> models: add audit log and user token tables

reana_db/models.py, reana_db/version.py, run-tests.sh, setup.py, tests/conftest.py, tests/test_models.py
closes reanahub/reana-server#235
=> models: add log action method for users

reana_db/config.py, reana_db/models.py, reana_db/version.py, setup.py
=> models: encrypt user token value

.travis.yml, MANIFEST.in, reana_db/alembic.ini, reana_db/alembic/env.py, reana_db/alembic/script.py.mako, reana_db/cli.py, reana_db/database.py, reana_db/models.py, reana_db/version.py, run-tests.sh, setup.py, tests/conftest.py, tests/test_models.py
* Wraps alembic command to enable database upgrades (closes reanahub/reana#336).
=> cli: add reana-db command

reana_db/models.py, reana_db/version.py
closes reanahub/reana-server#180
=> models: make User.workflows lazy dynamic

reana_db/database.py, reana_db/version.py
=> database: create schema only if it doesn't exist

AUTHORS.rst, CHANGES.rst, reana_db/models.py, setup.py
closes https://github.com/reanahub/reana-server/issues/279
=> models: add disk usage methods for User and Workflow models

reana_db/alembic/versions/20200928_1015_c912d4f1e1cc_quota_tables.py, reana_db/models.py, reana_db/version.py
=> models: add Quota models

reana_db/alembic/versions/20200928_1015_c912d4f1e1cc_quota_tables.py, reana_db/cli.py, reana_db/config.py, reana_db/models.py, reana_db/version.py, tests/conftest.py, tests/test_models.py
Closes reanahub/reana-workflow-controller#332, closes https://github.com/reanahub/reana/issues/415.
=> quotas: calculate quota usage for workflows

reana_db/cli.py, reana_db/models.py, reana_db/version.py, tests/conftest.py, tests/test_models.py
* Closes reanahub/reana-server#289.
=> models: overall user quota consumption

reana_db/models.py, setup.py, tests/test_models.py
* Closes reanahub/reana-server#296.
=> models: provide human readable quota usage

reana_db/config.py, reana_db/models.py
=> models: add default quota limits per resource type

reana_db/version.py
Closes https://github.com/reanahub/reana-server/issues/302.
=> release: 0.8.0a6

reana_db/models.py, reana_db/utils.py, tests/conftest.py
* Refactors `workflow_status_change_listener` to clearly show what
are the actions to be taken according to the new status.
* Updates workflow disk usage on workflow deletion
(closes reanahub/reana-db#100).
=> models: update workflow disk usage on delete

reana_db/cli.py, reana_db/models.py, reana_db/utils.py, reana_db/version.py, tests/conftest.py
Due to reana-client py2 tests breaking
addresses reanahub/reana-client#436
=> global: replace f-string with format

reana_db/alembic/versions/20200928_1015_c912d4f1e1cc_quota_tables.py, reana_db/alembic/versions/20201009_1612_ad93dae04483_interactive_sessions.py, reana_db/models.py, reana_db/utils.py, reana_db/version.py, setup.py, tests/test_models.py
* Creates a quota related operations mixin to propagate quota
calculation to different objects (workflows, interactive sessions...)
(closes reanahub/reana-server#296).
=> quotas: add QuotaBase mixin

reana_db/models.py, reana_db/version.py
closes reanahub/reana-server#282
=> models: add function to check if quota is exceeded

.github/workflows/ci.yml, setup.py
=>  ci: added python 2.7 to github action python test strategy

reana_db/models.py
=> ci: added python 2.7 to github action python test strategy #109

CHANGES.rst, reana_db/utils.py, reana_db/version.py
Allows passing raw bytes to increase the used quota.
closes reanahub/reana-workflow-controller#339
=> utils: enrich disk quota calculation functions

.flake8, .github/workflows/ci.yml, MANIFEST.in, reana_db/utils.py, run-tests.sh, setup.py
addresses https://github.com/reanahub/reana/issues/456
=> ci: added flake8 linter

CHANGES.rst, reana_db/models.py, reana_db/version.py, setup.py, tests/test_models.py
* Addresses reanahub/reana#461.
=> models: status enums to decide when to clean jobs

CHANGES.rst, reana_db/version.py, setup.py
Closes reanahub/reana-job-controller#304.
=> installation: temporarily pin SQLAlchemy<1.4 

CHANGES.rst, reana_db/models.py, reana_db/version.py
Closes reanahub/reana-client#497.
=> models: add start and finish times for jobs

CHANGES.rst, reana_db/models.py, tests/conftest.py, tests/test_models.py
Closes reanahub/reana-server#356
=> models: add workflow priority property

reana_db/models.py
closes https://github.com/reanahub/reana-client/issues/522
=> workflow: add search param in workflow_disk_usage

AUTHORS.rst, CHANGES.rst, reana_db/version.py, setup.py
=> release: 0.8.1

CHANGES.rst, reana_db/models.py, reana_db/version.py, tests/test_models.py
closes reanahub/reana-server#436
=> models: allow workflow to fail from queued status

CHANGES.rst, reana_db/alembic/versions/20220307_1247_d34f3905043c_workflow_launcher_url.py, reana_db/models.py, reana_db/version.py
=> models: add `launcher_url` column to `Workflow` table

reana_db/models.py, reana_db/version.py
addresses https://github.com/reanahub/reana-ui/issues/222
=> models: add missing `launcher_url` on constructor

AUTHORS.rst, reana_db/utils.py
=> utils: add possibility to skip the policy checks when updating quotas

CHANGES.rst, reana_db/alembic/versions/20221006_1140_377cfbfccf75_retention_rules_pending_status.py, reana_db/models.py, reana_db/version.py, setup.py, tests/test_models.py
Closes reanahub/reana-server#526
=> models: add `pending` status for retention rules

reana_db/utils.py, tests/conftest.py, tests/test_utils.py
Check that the current user is the owner of the workflow when searching by UUID.
=> utils: check user is the owner of the workflow

CHANGES.rst, reana_db/models.py, reana_db/utils.py, tests/test_models.py
=> models: fix human-readable conversion with negative resource amounts

CHANGES.rst, reana_db/cli.py, reana_db/utils.py, reana_db/version.py, setup.py
=> quotas: partially load workflows to reduce memory usage

.readthedocs.yaml, MANIFEST.in, tests/test_models.py, tests/test_utils.py
=> docs: add .readthedocs.yaml to migrate to RTD v2

CHANGES.rst, reana_db/version.py, setup.py
=> release: 0.9.3

run-tests.sh
=> ci(pytest): move to PostgreSQL 14.10 (#226)
